### ISSUE TITLE
Add a list of contributors and their contributions to the release page

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/community#57]
To recognize contributors, lets add a section to the release page mentioning their name and PRs. For example - https://github.com/openshift/oadp-operator/releases/tag/v1.1.0

@djzager @jmontleon is this something that can be added to the automation? 

cc: @pranavgaikwad @jwmatthews

**Comment by djzager** [comment]
@kaovilai you may have mentioned previously, but how are the new contributors retrieved?

**Comment by kaovilai** [comment]
It's automatic from the GitHub auto generate release notes

**Comment by kaovilai** [comment]
<img width="990" alt="image" src="https://github.com/konveyor/community/assets/11228024/f59a143e-e105-437f-ae2e-1bccb3f4a5d5">
<img width="1000" alt="image" src="https://github.com/konveyor/community/assets/11228024/6ec95045-9d82-4589-8c64-4b74649cb731">

**Comment by kaovilai** [comment]
If you wanna automate this I have an example workflows that retrieves this data from github rest api at https://github.com/kaovilai/oadp-release-notes

Please take a look there. Use it to generate this automated text then perhaps grep for ## New Contributors and collect usernames.
