### ISSUE TITLE
Add @dymurray to the list of Maintainers

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/community#82]
### Description

Hi All, 

I would like to propose adding Dylan (@dymurray ) to the list of Maintainers. Dylan has been an active contributor of the Konveyor community. He has been leading multiple efforts like Konveyor planning, triage, end user interactions, and many more. He would be a great addition to the leadership. 

Inviting the steering committee members to vote in this issue with a +1 (yes) or -1 (no) registering their choice - @jwmatthews @tsanders-rh @rromannissen @JonathanR19 @tamintheclouds 

Please feel free to reach out if you have any questions.

**Comment by savitharaghunathan** [comment]
with my Steering hat on, +1 from me

**Comment by jwmatthews** [comment]
+1

**Comment by JonathanR19** [comment]
+1

**Comment by tsanders-rh** [comment]
+1

**Comment by savitharaghunathan** [comment]
closed via https://github.com/konveyor/community/pull/83
